FROM scratch
MAINTAINER Arun Neelicattu <arun.neelicattu@gmail.com>

COPY ./rootfs/ /

VOLUME ["/var/log", "/var/run", "/etc/bird.d"]
EXPOSE 179/tcp

ENTRYPOINT ["/usr/sbin/bird"]
CMD ["-c", "/etc/bird.conf", "-s", "/var/run/bird.ctl", "-f"]
